---
#######################
## Set some DEFAULTS ##
#######################
hostname: "testing"
username: "USERNAME"
password: "PASSWORD"

timezone: "America/Los_Angeles"

## Rclone Crypt
#remote: 'GDRIVE'
#local: 'LOCAL'
#overlayfuse: 'ALL'

## Plex
#plexToken: ''
#plexUsername: ''
#plexPassword: ''

## NZBGet
#nzbGetTesting: 'no'

## OpenSubTitles
#openSubtitlesUsername: ''
#openSubtitlesPassword: ''
#openSubtitlesLang: ''

## News Server
#newsServer: ''
#nsHostname: ''
#nsPort: ''
#nsUsername: ''
#nsPassword: ''
#nsEncryption: 'yes'
#nsConnections: '20'
#nsRetention: '1000'

## ComicVine
# Optional Mylar / Comic Book Support
#comicvineAPI: ''

## rTorrent/ruTorrent
#torrentPort: '61347'

